Models/Competition.cs
using System.ComponentModel.DataAnnotations;


public class Competition
{
    [Key]
    public int CompetitionId { get; set; }
    public string Name { get; set; }
    public DateTime EventDate { get; set; }

    public string Location {get; set; }
    public string GameType { get; set; }
    public decimal PrizePool { get; set; }
    public string Description { get; set; }
}

Controllers/CompetitionController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using lan_week.Models;
using System.Linq;
using System.Threading.Tasks;

public class CompetitionController : Controller
{
    private readonly DatabaseManager _context;
    private readonly UserManager<IdentityUser> _userManager;

    public CompetitionController(DatabaseManager context, UserManager<IdentityUser> userManager)
    {
        _context = context;
        _userManager = userManager;
    }

    public async Task<IActionResult> Index()
    {
        var viewModel = new CompetitionIndexViewModel();

        viewModel.PastCompetitions = await _context.Competitions
            .Where(c => c.EventDate < DateTime.Now)
            .OrderByDescending(c => c.EventDate)
            .Take(3)
            .ToListAsync();

        if (User.Identity.IsAuthenticated)
        {
            viewModel.UpcomingCompetitions = await _context.Competitions
                .Where(c => c.EventDate >= DateTime.Now)
                .OrderBy(c => c.EventDate)
                .Take(3)
                .ToListAsync();
        }

        return View(viewModel);
    }

    [HttpGet]
    public async Task<IActionResult> Upcoming()
    {
        var upcomingCompetitions = await _context.Competitions
            .Where(c => c.EventDate >= DateTime.Now)
            .OrderBy(c => c.EventDate)
            .ToListAsync();

        return View(upcomingCompetitions);
    }

    [HttpGet]
    public async Task<IActionResult> Past()
    {
        var pastCompetitions = await _context.Competitions
            .Where(c => c.EventDate < DateTime.Now)
            .OrderByDescending(c => c.EventDate)
            .ToListAsync();

        return View(pastCompetitions);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View(new CreateCompetitionViewModel());
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Name,EventDate,Location,GameType,PrizePool,Description")] Competition competition)
    {
        if (ModelState.IsValid)
        {
            _context.Add(competition);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Upcoming));
        }
        return View(competition);
    }



    [HttpGet]
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var competition = await _context.Competitions
            .FirstOrDefaultAsync(m => m.CompetitionId == id);

        if (competition == null)
        {
            return NotFound();
        }

        return View(competition);
    }
    
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var competition = await _context.Competitions.FindAsync(id);
        if (competition == null)
        {
            return NotFound();
        }

        return View(competition);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("CompetitionId,Name,EventDate,GameType,PrizePool,Description,Location")] Competition competition)
    {
        if (id != competition.CompetitionId)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(competition);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CompetitionExists(competition.CompetitionId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(competition);
    }

    private bool CompetitionExists(int id)
    {
        return _context.Competitions.Any(e => e.CompetitionId == id);
    }

}

Views/Competition/Create.cshtml
@model CreateCompetitionViewModel

@{
    ViewData["Title"] = "Create Competition";
}


<h2>Create Competition</h2>

<form asp-action="Create" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="EventDate"></label>
        <input asp-for="EventDate" class="form-control" />
        <span asp-validation-for="EventDate" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Location"></label>
        <input asp-for="Location" class="form-control" />
        <span asp-validation-for="Location" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="GameType"></label>
        <input asp-for="GameType" class="form-control" />
        <span asp-validation-for="GameType" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PrizePool"></label>
        <input asp-for="PrizePool" class="form-control" />
        <span asp-validation-for="PrizePool" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>


    <button type="submit" class="btn btn-primary">Create</button>
</form>

Views/Competition/Details.cshtml
@model Competition

@{
    ViewData["Title"] = "Competition Details";
}

<h2>@Model.Name</h2>

<div>
    <h4>Competition Details</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Event Date - Location
        </dt>
        <dd class="col-sm-10">
            @Model.EventDate.ToString("yyyy-MM-dd") - @Model.Location
        </dd>
        <dt class="col-sm-2">
            Game Type
        </dt>
        <dd class="col-sm-10">
            @Model.GameType
        </dd>
        <dt class="col-sm-2">
            Prize Pool
        </dt>
        <dd class="col-sm-10">
            @Model.PrizePool
        </dd>
        <dt class="col-sm-2">
            Description
        </dt>
        <dd class="col-sm-10">
            @Model.Description
        </dd>
    </dl>
</div>
<div>
    @if (User.Identity.IsAuthenticated)
{
    <div>
    <a asp-action="Edit" asp-route-id="@Model.CompetitionId">Edit</a> |
    <a asp-action="Index">Back Competitions</a>
    </div>
    } 
    else
    {
        <a asp-action="Index">Back Competitions</a>
    } 
</div>

Views/Competition/Edit.cshtml
@model Competition

@{
    ViewData["Title"] = "Edit Competition";
}

<h2>Edit Competition</h2>

<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="CompetitionId" />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="EventDate"></label>
        <input asp-for="EventDate" class="form-control" type="date" />
        <span asp-validation-for="EventDate" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="GameType"></label>
        <input asp-for="GameType" class="form-control" />
        <span asp-validation-for="GameType" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PrizePool"></label>
        <input asp-for="PrizePool" class="form-control" />
        <span asp-validation-for="PrizePool" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Location"></label>
        <input asp-for="Location" class="form-control" />
        <span asp-validation-for="Location" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
</form>

<div>
    <a asp-action="Details" asp-route-id="@Model.CompetitionId">Back to Details</a>
</div>

Views/Competition/Index.cshtml
@model CompetitionIndexViewModel
@if (User.Identity.IsAuthenticated)
{
    <h1>Upcoming Competitions</h1>
    @foreach (var competition in Model.UpcomingCompetitions)
    {
        <div>
            <h4>@competition.Name</h4>
            <h4>@competition.GameType</h4>
            <p>Date: @competition.EventDate.ToString("yyyy-MM-dd")</p>
            <p>GameType: @competition.GameType</p>
            <p>PrizePool: @competition.PrizePool</p>
            <p>Description: @competition.Description</p>
            <a asp-controller="Competition" asp-action="Details" asp-route-id="@competition.CompetitionId">Results</a>
        </div>
    }
}
<h1>Past Competitions</h1>
@foreach (var competition in Model.PastCompetitions)
{
    <div>
        <h4>@competition.Name</h4>
        <h4>@competition.GameType</h4>
        <p>Date: @competition.EventDate.ToString("yyyy-MM-dd")</p>
        <p>GameType: @competition.GameType</p>
        <p>PrizePool: @competition.PrizePool</p>
        <p>Description: @competition.Description</p>
        <a asp-controller="Competition" asp-action="Details" asp-route-id="@competition.CompetitionId">Results</a>
    </div>
}

Views/Competition/Past.cshtml
@model IEnumerable<Competition>

<h2>Past Competitions</h2>

@foreach (var competition in Model)
{
    <div>
        <h3>@competition.GameType</h3>
        <p>Date: @competition.EventDate.ToString("yyyy-MM-dd") - @competition.Location</p>
        <p>GameType: @competition.GameType</p>
        <p>PrizePool: @competition.PrizePool</p>
        <p>Description: @competition.Description</p>
        <a asp-controller="Competition" asp-action="Details" asp-route-id="@competition.CompetitionId">Results</a>
    </div>
}

Views/Competition/Upcoming.cshtml
@model IEnumerable<Competition>

@{
    ViewData["Title"] = "Upcoming Competitions";
}


<h2>Upcoming Competitions</h2>

@foreach (var competition in Model)
{
    <div>
        <h3>@competition.Name</h3>
        <p>Date: @competition.EventDate.ToString("yyyy-MM-dd") - @competition.Location</p>
        <p>GameType: @competition.GameType</p>
        <p>PrizePool: @competition.PrizePool</p>
        <p>Description: @competition.Description</p>
        <!-- Link to join or view more details -->
        <a asp-controller="Competition" asp-action="Details" asp-route-id="@competition.CompetitionId">Details</a>
    </div>
}